## Please do not modify this file

Cells.HF = c("Mononuclear cells from peripheral blood",
             "T cells CD3+",
             "T cells effector/memory CD4+ CD25int CD127+",
             "T regulatory cells CD4+ CD25+ CD127-",
             "T helper cells CD4+ CD25-",
             "T helper naive cells CD4+ CD25- CD45RA+",
             "T helper cells PMA-I stimulated CD4+ CD25- IL17-",
             "T helper 17 cells PMA-I stimulated CD4+ CD25- IL17+",
             "T helper memory cells CD4+ CD25- CD45RO+",
             "T helper memory cells from peripheral blood CD4+",
             "T memory cells CD8+",
             "T helper naive cells CD4+",
             "T naive cells CD8+",
             "Monocytes CD14+",
             "Hematopoietic stem cells G-CSF-mobilized CD34+",
             "B cells CD19+",
             "Natural killer cells CD56+",
             "GM12878 lymphoblastoid cells",
             "Thymus",
             "Spleen",
             "Brain hippocampus middle",
             "Brain substantia nigra",
             "Brain anterior caudate",
             "Brain cingulate gyrus",
             "Brain inferior temporal lobe",
             "Brain angular gyrus",
             "Brain dorsolateral prefrontal cortex",
             "NH-A astrocytes",
             "Lung",
             "NHLF lung fibroblast primary cells",
             "Aorta",
             "HUVEC umbilical vein endothelial primary cells",
             "Right atrium",
             "Left ventricle",
             "Right ventricle",
             "Muscle satellite cultured cells",
             "Psoas muscle",
             "Skeletal muscle",
             "HSMM skeletal muscle myoblasts cells",
             "HSMM cell derived skeletal muscle myotubes cells",
             "Stomach smooth muscle",
             "Duodenum smooth muscle",
             "Colon smooth muscle",
             "Rectal smooth muscle",
             "Esophagus",
             "Gastric",
             "Stomach mucosa",
             "Duodenum mucosa",
             "Small intestine",
             "Sigmoid colon",
             "Colonic mucosa",
             "Rectal mucosa",
             "Pancreas",
             "Pancreatic islets",
             "Liver",
             "Adipose nuclei",
             "Adipose derived mesenchymal stem cell cultured cells",
             "Mesenchymal stem cell derived adipocyte cultured cells",
             "Mesenchymal stem cell derived chondrocyte cultured cells",
             "Bone marrow derived cultured mesenchymal stem cells",
             "Osteoblast primary cells",
             "Foreskin fibroblast primary cells",
             "Foreskin melanocyte primary cells",
             "Foreskin keratinocyte primary cells",
             "NHDF-Ad adult dermal fibroblast primary cells",
             "NHEK-epidermal keratinocyteprimary cells",
             "Breast myoepithelial primary cells",
             "Breast variant human mammary epithelial cells (vHMEC)",
             "HMEC mammary epithelial primary cells",
             "Ovary")







